#!/bin/bash
# 세션 종료 시 세션 크기 리포트
# Hook Type: Stop
# 설정: ~/.claude/settings.json의 hooks 배열에 추가

# 동적 경로: 현재 PWD 기반으로 세션 디렉토리 계산
SESSION_DIR="$HOME/.claude/projects/-$(echo "$PWD" | tr '/' '-' | sed 's/^-//')"

if [ -d "$SESSION_DIR" ]; then
    # 가장 최근 세션 파일 찾기
    CURRENT_SESSION=$(ls -t "$SESSION_DIR"/*.jsonl 2>/dev/null | head -1)

    if [ -n "$CURRENT_SESSION" ]; then
        SIZE=$(ls -lh "$CURRENT_SESSION" | awk '{print $5}')
        LINES=$(wc -l < "$CURRENT_SESSION" 2>/dev/null || echo "0")

        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "📊 세션 리포트"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "📁 크기: $SIZE"
        echo "📝 메시지: ~$LINES 개"

        # 크기 경고
        SIZE_MB=$(echo "$SIZE" | sed 's/M$//' | sed 's/K$/0.001/' | sed 's/G$/1000/')
        if (( $(echo "$SIZE_MB > 20" | bc -l 2>/dev/null || echo 0) )); then
            echo "⚠️  상태: 🔴 위험 - 새 세션 권장!"
        elif (( $(echo "$SIZE_MB > 10" | bc -l 2>/dev/null || echo 0) )); then
            echo "⚠️  상태: 🟠 경고 - /compact 권장"
        elif (( $(echo "$SIZE_MB > 5" | bc -l 2>/dev/null || echo 0) )); then
            echo "⚠️  상태: 🟡 주의"
        else
            echo "✅ 상태: 🟢 정상"
        fi
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        # Phase 0 준수 여부 (autonomous 모드일 때만)
        PANE_ID=$(echo "$TMUX_PANE" | tr -d '%')
        SUFFIX="${PANE_ID:+-pane$PANE_ID}"
        AUTONOMOUS_FILE="$HOME/.claude/state/AUTONOMOUS_MODE${SUFFIX}"
        if [ -f "$AUTONOMOUS_FILE" ]; then
            echo "🤖 모드: Autonomous"
            if grep -q "nlm notebook query" "$CURRENT_SESSION" 2>/dev/null; then
                echo "✅ Phase 0 nlm: 실행됨"
            else
                echo "🔴 Phase 0 nlm: 미실행 (규칙 위반)"
            fi
        fi

        # --- 자동 핸드오프 (v5.19) ---
        # TASK_COMPLETE가 있으면 = 정상 종료 → 핸드오프 불필요
        if [ ! -f "$HOME/.claude/state/TASK_COMPLETE${SUFFIX}" ]; then
            # session ID 추출 (JSONL 파일명 앞 8자)
            SESSION_ID=$(basename "$CURRENT_SESSION" .jsonl | cut -c1-8)

            # 최근 5분 이내 같은 프로젝트 핸드오프가 있으면 건너뛰기
            HANDOFF_DIR="$HOME/.claude/state/handoffs"
            SKIP_HANDOFF=0
            if [ -d "$HANDOFF_DIR" ]; then
                for f in "$HANDOFF_DIR"/handoff-*.md; do
                    [ -f "$f" ] || continue
                    age=$(( $(date +%s) - $(stat -f %m "$f") ))
                    proj=$(grep "^- project:" "$f" 2>/dev/null | sed 's/^- project: //')
                    if [ "$age" -lt 300 ] && [ "$proj" = "$PWD" ]; then
                        SKIP_HANDOFF=1
                        break
                    fi
                done
            fi

            if [ "$SKIP_HANDOFF" -eq 0 ]; then
                # JSONL에서 마지막 유의미한 assistant 텍스트 추출
                TASK=$(tail -c 100000 "$CURRENT_SESSION" | python3 -c "
import sys, json
last = ''
for line in sys.stdin:
    try:
        obj = json.loads(line.strip())
        if obj.get('type') == 'assistant':
            for c in obj.get('message',{}).get('content',[]):
                t = c.get('text','')
                if len(t) > 30: last = t[:200]
    except: pass
print(last)
" 2>/dev/null)

                if [ ${#TASK} -gt 30 ]; then
                    mkdir -p "$HANDOFF_DIR"
                    PANE_LABEL="${PANE_ID:-x}"
                    HEX=$(openssl rand -hex 3)
                    cat > "$HANDOFF_DIR/handoff-$(date +%s)-pane${PANE_LABEL}-${HEX}.md" << HANDOFF_EOF
# Session Handoff (auto-generated by stop hook)
- session: ${SESSION_ID}
- pane: ${PANE_LABEL}
- project: $PWD
- task: ${TASK}
- timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
HANDOFF_EOF
                    echo "📋 핸드오프 자동 생성 (session: ${SESSION_ID})"
                fi
            fi
        fi
    fi
fi
